### ISSUE TITLE
How to create a ByteVerifier within a JsonWebSignature2020LdVerifier?

### ISSUE THREAD

**Issue by 8sd** [WebOfTrustInfo/ld-signatures-java#17]
Hi,

I'm currently developing the validation of a Linked Data Proof.
I followed the development [examples](https://github.com/danubetech/verifiable-credentials-java/blob/main/examples-ldp-vp.md#example-code-verifying) to implement the code:

```
VerifiablePresentation presentation = VerifiablePresentation.fromJson(json);
LdVerifier verifier = new JsonWebSignature2020LdVerifier();
verifier.verify(presentation);
```

Unfortunately, the function `verify` throws a `NullPointerException` when [getting the Algorithm](https://github.com/WebOfTrustInfo/ld-signatures-java/blob/81c2720534b1b9c0ade8f7bc4d554e2605c95cd5/src/main/java/info/weboftrust/ldsignatures/verifier/JsonWebSignature2020LdVerifier.java#L44) from the `verifier`.

I would have thought that the suiting `verifier` is chosen automatically depending on the to-be-verified JWS. 
Now I'm trying to generate the `verifier` manually. However, I fail to do it. I fail somewhere in generating the RSA Keys manually.
Also, it doesn't feel like doing it correctly since the algorithm might change in different JWSs.

Do I miss something here?
How can this issue be resolved?

I really appreciate any help you can provide.
Sebastian

**Comment by peacekeeper** [comment]
Hello @8sd thanks for your question. Would you mind posting here the value of the "json" variable, i.e. the VP you are trying to verify?

**Comment by 8sd** [comment]
Hello @peacekeeper, 
thanks for reaching out.

I sent you the JSON via mail since I'm not sure if I'm allowed to share it publicly.

I don't try to create RSA keys. The RSA keys should be determined by the `verificationMethod`. However, since `JsonWebSignature2020LdVerifier` doesn't do it, I tried to create the RSA public key object manually.

**Comment by peacekeeper** [comment]
Okay, so you have to construct an instance of a `ByteVerifier`, otherwise the `JsonWebSignature2020LdVerifier` wouldn't know which public key to use for the verification.

I assume you have the corresponding public key somewhere, maybe in JWK format?

In that case, one way how you can construct the `ByteVerifier` is like this:

```
JWK jwk = JWK.fromJson(jwkJson);
PublicKeyVerifier<?> publicKeyVerifier = PublicKeyVerifierFactory.publicKeyVerifierForKey(
    KeyTypeName_for_JWK.keyTypeName_for_JWK(jwk),
    JWSAlgorithm.PS256,
    JWK_to_PublicKey.JWK_to_anyPublicKey(jwk));
```

You can then initialize the `JsonWebSignature2020LdVerifier` as follows:

```
LdVerifier verifier = new JsonWebSignature2020LdVerifier(publicKeyVerifier);
```

I just pushed a commit to `key-formats-java` with a convenience method that should make this a bit easier: https://github.com/danubetech/key-formats-java/commit/0b515d1452b0786226cac6fa98832bbf10bac6b7

Does this help?

**Comment by 8sd** [comment]
Yes, this helps very much!

Thanks. I was unaware that I must build the PublicKeyVerifier manually, but your snipped helped.

**Comment by 8sd** [comment]
Since the verification is working now, I want to sign VCs and VPs.
So far, I came up with the following code:

```
VerifiableCredential vc = VerifiableCredential.fromJson(<string>);

        PrivateKeySigner pkSigner = new PrivateKeySigner;
        LdSigner signer = new JsonWebSignature2020LdSigner(pkSigner);

        signer.setCreated(new Date());
        signer.setProofPurpose(LDSecurityKeywords.JSONLD_TERM_ASSERTIONMETHOD);
        signer.setVerificationMethod(URI.create("did:web:..."));

        LdProof ldProof = signer.sign(vc);
```

Now I'm asking myself how to create the ByteSigner `pkSigner`.
Do you have an example, of how to do this based on an x509 certificate?

Thanks in advance!

**Comment by peacekeeper** [comment]
Hello again.. If you have the private key in JWK form, then this should work in a similar way as before, e.g.:

```
        PrivateKeySigner<?> privateKeySigner = PrivateKeySignerFactory.privateKeySignerForKey(
                KeyTypeName_for_JWK.keyTypeName_for_JWK(jwk),
                JWSAlgorithm.PS256,
                JWK_to_PrivateKey.JWK_to_anyPrivateKey(jwk));
```

If you have an instance of **java.security.KeyPair**, you could do it like this:

```
        PrivateKeySigner<?> privateKeySigner = new RSA_PS256_PrivateKeySigner(keyPair);
```

Does this help?

**Comment by 8sd** [comment]
Since the verification is working now, I want to sign VCs and VPs.
So far, I came up with the following code:

```
VerifiableCredential vc = VerifiableCredential.fromJson(<string>);

        PrivateKeySigner pkSigner = new PrivateKeySigner;
        LdSigner signer = new JsonWebSignature2020LdSigner(pkSigner);

        signer.setCreated(new Date());
        signer.setProofPurpose(LDSecurityKeywords.JSONLD_TERM_ASSERTIONMETHOD);
        signer.setVerificationMethod(URI.create("did:web:..."));

        LdProof ldProof = signer.sign(vc);
```

Now I'm asking myself how to create the ByteSigner `pkSigner`.
Do you have an example, of how to do this based on an x509 certificate?

Thanks in advance!

**Comment by 8sd** [comment]
Hi peacekeeper, 

thanks for your answer. I think it helped.

When I'm signing and verifying VPs/VCs with your library, are they normalized using URDNA2015?

Thanks in advance.

**Comment by peacekeeper** [comment]
Yes, URDNA2015 is used for most of the signature suites (e.g. [Ed25519Signature2020LdSigner](https://github.com/WebOfTrustInfo/ld-signatures-java/blob/main/src/main/java/info/weboftrust/ldsignatures/signer/Ed25519Signature2020LdSigner.java), [EcdsaSecp256k1Signature2019LdSigner](https://github.com/WebOfTrustInfo/ld-signatures-java/blob/main/src/main/java/info/weboftrust/ldsignatures/signer/EcdsaSecp256k1Signature2019LdSigner.java), etc.)

Some of the signature suites use JCS instead (e.g. [JcsEd25519Signature2020LdSigner](https://github.com/WebOfTrustInfo/ld-signatures-java/blob/main/src/main/java/info/weboftrust/ldsignatures/signer/JcsEd25519Signature2020LdSigner.java), etc.)

**Comment by 8sd** [comment]
Now, the code works. Thanks for your awesome help! 👍
